version: '3.3'

services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - wagtail
      # add a volume to image
    volumes:
      - mediawt:/usr/share/nginx/mediawt

  wagtail:
    build: .
    expose:
      - '8000'
    environment:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    depends_on:
      - db
      - redis
    # desarrollo
    # command: python manage.py runserver 0.0.0.0:8000
    # produccion -> gunicorn proyecto
    command: gunicorn bakerydemo.wsgi:application --bind 0.0.0.0:8000

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    expose:
      - '5432'

    volumes:
      - dbbakery:/var/lib/postgresql/data
      - ./backup:/backup
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=db

  redis:
    image: redis:latest
    restart: always
    expose:
      - '6379'

volumes:
  dbbakery:
    driver: local
