version: '3.3'
services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 1337:80
    depends_on:
      - wagtail # el nombre que hayamo dado al servicio de nuestra web
  wagtail:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000
  
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

    ports:
      - '5432:5432'
    
    volumes: 
      - dbbakery:/var/lib/postgresql/data
      - ./backup:/backup
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 81:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

volumes:
  dbbakery:
    driver: local